apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: mywebchat 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mywebchat 
    spec:
      progressDeadlineSeconds:600
      containers:
        - name: mywebchat 
          image: mycontainertestkk.azurecr.io/mywebchat
          ports:
          - containerPort: 8888