apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: mywebchat 
spec:
  replicas: 1
  strategy:
  	type: RollingUpdate
  	rollingUpdate:
    	maxSurge: 0
    	maxUnavailable: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mywebchat 
    spec:
      containers:
        - name: mywebchat 
          image: mycontainertestkk.azurecr.io/mywebchat
          ports:
          - containerPort: 8888